### ISSUE TITLE
XML

### ISSUE THREAD

**Issue by RaHoni** [RaHoni/PrivateHome#3]
XML Datei für alle Schalter
XML Datei 433MHz Code zu ID

**Comment by maximiliani** [comment]
Speichern bei:
- Änderung Gerätemap
- Statusänderung von ausgewählten Geräten
- sonstige Einstellungen

**Comment by maximiliani** [comment]
Mithilfe der editXML.scala können nun in die devices.xml und die id.xml Objekte hinzugefügt werden, die den Verlust der Daten verhindern. Die Funktion addObject(Object:object) muss jedes Mal, wenn ein Gerät hinzugefügt wird ausgeführt werden!

**Comment by maximiliani** [comment]
Mithilfe der editXML.scala können nun auch XMLObjekte hinzugefügt/gelöscht/geladen und gesichert werden. Eigentlich habe ich alles einmal überarbeitet. Die alte Funktion editXML.addObject ist dabei rausgeflogen. War eh nur 💩!
